# Spring Application Name
spring.application.name=atelier-platform

# Database Configuration
spring.jpa.database=POSTGRESQL
spring.datasource.platfrom=postgres
spring.datasource.url=jdbc:postgresql://atelier-database-atelier-project.d.aivencloud.com:19969/atelierdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true