# Spring Application Name
spring.application.name=atelier-platform

# Database Configuration
spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://atelier-database-atelier-project.d.aivencloud.com:19969/atelierdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=com.andeva.atelier.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:atelier.support.team@gmail.com}
spring.mail.password=${MAIL_PASSWORD:pwprrzholvsyneue}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
authorization.jwt.secret=${JWT_SECRET:ZXN0YS1lcy11bmEtY2xhdmUtc2VjcmV0YS1wb3ItZGVmZWN0by1tdXktbGFyZ2EtcGFyYS1kZXNhcnJvbGxvLWxvY2FsLWp3dA==}
authorization.jwt.expiration.days=7

# Application Settings
app.frontend.url=https://atelier-sepia-three.vercel.app
